#!/usr/bin/env bash

: << !
Name: 2-install-packages
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:32:42

Description: 基于软件包列表文件批量安装 Arch Linux 官方仓库中的软件包
- 参考该链接 https://wiki.archlinuxcn.org/wiki/Pacman/%E6%8F%90%E7%A4%BA%E5%92%8C%E6%8A%80%E5%B7%A7#%E4%BB%8E%E5%88%97%E8%A1%A8%E5%AE%89%E8%A3%85%E8%BD%AF%E4%BB%B6%E5%8C%85

Attentions:
- 需要先使用 1-manage-pacman 添加 archlinuxcn 源
- 需要 root 权限

Depends:
- pacman
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.0.6
readonly minor_version=20231013
readonly rel_version=1

#------------------------- Exit Code Variable
readonly err_file=1      # 文件/路径类错误
readonly err_ctrl_c=130  # 接收到 INT(Ctrl+C) 指令
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="batch installation of software packages in the Arch Linux official repository based on the package list file"
# path variable
package_list_file="$HOME/Documents/Repos/System/Profile/home/yj/dot_cache/SpiderData/PackageList/Pacman.list"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m \x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function exitProgram() {
  echo -e "Ctrl+C is captured, exit"
  exit $err_ctrl_c
}

function main() {
  while true; do
    trap 'exitProgram' INT # 捕获到 INT(Ctrl+C) 信号，程序退出

    if [[ -s $package_list_file ]]; then
      pacman -S --needed - < "$package_list_file"
    else
      exit $err_file
    fi
  done
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  main
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
