#!/usr/bin/env bash

: << !
Name: 3-init-root
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2023-04-10 10:00:17

Description: 初始化root账户

Attentions:
-登录到root账户而非使用sudo提权使用

Depends:
-
!
####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=0.0.3
readonly minor_version=20231013
readonly rel_version=1

#------------------------- Exit Code Variable
readonly err_permission=110 # 权限错误
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="初始化root账户"
# 主目录设置
readonly yj_home="/home/yj"
readonly root_home="/root"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m\x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help        显示帮助信息"
  echo -e "     -v, --version     显示版本信息"
  echo -e ""
  echo -e "Notice:"
  echo -e "    \x1b[5m需要登录到root账户而非通过sudo提权使用\x1b[0m"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function checkUser() {
  if [[ $USER != "$1" ]]; then
    echo -e "\n\x1b[31m[✘]\x1b[0m 当前用户不是$1，拒绝执行"
    exit $err_permission
  fi
}

function main() {
  # 更改登录shell
  echo -e "\x1b[32;3m正在配置登录shell\x1b[0m"
  chsh -s /bin/zsh root
  # 配置shell
  echo -e "\x1b[32;3m正在配置zsh\x1b[0m"
  ln -sf "$yj_home"/.zshrc "$root_home"/.zshrc
  ln -sf "$yj_home"/.bashrc "$root_home"/.bashrc
  ln -sf "$yj_home"/.p10k.zsh "$root_home"/.p10k.zsh
  # 更新XDG用户目录
  echo -e "\x1b[32;3m正在配置user-dirs\x1b[0m"
  mkdir "$root_home/Desktop" "$root_home/Downloads" "$root_home/Documents" "$root_home/Music" "$root_home/Pictures" "$root_home/Videos" "$root_home/.Public" "$root_home/.Templates"
  ln -sf "$yj_home"/.config/user-dirs.locale "$root_home"/.config/user-dirs.locale
  ln -sf "$yj_home"/.config/user-dirs.dirs "$root_home"/.config/user-dirs.dirs
  xdg-user-dirs-update
  # 配置git
  echo -e "\x1b[32;3m正在配置git\x1b[0m"
  ln -sf "$yj_home"/.gitconfig "$root_home"/.gitconfig
  # 配置npm
  echo -e "\x1b[32;3m正在配置npm\x1b[0m"
  ln -sf "$yj_home"/.npmrc "$root_home"/.npmrc
  # 安装并配置space-vim
  echo -e "\x1b[32;3m正在配置space-vim\x1b[0m"
  cp "$yj_home"/Documents/Repos/System/Program/Script/install/install-spacevim ~/Desktop
  cd ~/Desktop || exit 1 && bash install-spacevim && rm -f ~/Desktop/install-spacevim
  ln -sf "$yj_home"/.spacevim "$root_home"/.spacevim
  ln -sf "$yj_home"/.config/nvim/coc-settings.json "$root_home"/.config/nvim/coc-settings.json
  ln -sf "$yj_home"/.space-vim/private/config.vim "$root_home"/.space-vim/private/config.vim
  ln -sf "$yj_home"/.space-vim/private/packages.vim "$root_home"/.space-vim/private/packages.vim
  ln -sf "$yj_home"/.space-vim/private/README.md "$root_home"/.space-vim/private/README.md
  ln -sf "$yj_home"/.space-vim/private/Layers.md "$root_home"/.space-vim/private/Layers.md
  # 配置dtags
  echo -e "\x1b[32;3m正在配置dtags\x1b[0m"
  mkdir "$root_home"/.dtags
  ln -sf "$yj_home"/.dtags/completion "$root_home"/.dtags/completion
  ln -sf "$yj_home"/.dtags/config.json "$root_home"/.dtags/config.json
  # 配置ssh客户端
  echo -e "\x1b[32;3m正在配置ssh\x1b[0m"
  mkdir "$root_home"/.ssh && ln -sf "$yj_home"/.ssh/config "$root_home"/.ssh/config
  # 配置yay
  echo -e "\x1b[32;3m正在配置yay\x1b[0m"
  mkdir "$root_home"/.config/yay && ln -sf "$yj_home"/.config/yay/config.json "$root_home"/.config/yay/config.json
  # 配置tldr
  echo -e "\x1b[32;3m正在配置tldr\x1b[0m"
  mkdir "$root_home"/.config/tealdeer && ln -sf "$yj_home"/.config/tealdeer/config.toml "$root_home"/.config/tealdeer/config.toml
  # 配置neofetch
  echo -e "\x1b[32;3m正在配置neofetch\x1b[0m"
  mkdir "$root_home"/.config/neofetch && ln -sf "$yj_home"/.config/neofetch/config.conf "$root_home"/.config/neofetch/config.conf
  # 配置go
  echo -e "\x1b[32;3m正在配置go\x1b[0m"
  mkdir "$root_home"/.config/go && ln -sf "$yj_home"/.config/go/env "$root_home"/.config/go/env
  echo -e "完成"
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  checkUser "root"
  main
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
