#!/usr/bin/env bash

: << !
Name: clone-my-repos
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 11:03:49

Description: 克隆我的GitHub仓库

Attentions:
-

Depends:
- git
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.3.3
readonly minor_version=20230316
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_file=1         # 文件/路径类错误
readonly err_param=2        # 参数错误
readonly err_no_program=127 # 未找到命令
readonly err_permission=110 # 权限错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于克隆我的GitHub仓库"

#------------------------- Parameter Variable
# path variable
readonly path="$HOME/Documents/MyRepos"
readonly repos=(
  YHYJ
  System TimeNote
  LearningCenter
  LogWrapper Program-module
  checker rolling scleaner
  MyBlogs MyDocker MyDockerfile MyRaspberry MyShell MyWiki
  DataCollector DataWizard SystemMonitor Sniffer OPC2Socket Devicer WeatherStation
  Test
)

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function checkUser() {
  if [[ $USER == "$1" ]]; then
    echo -e "\n\033[31m[✘]\033[0m 当前用户是$1，拒绝执行"
    exit $err_permission
  fi
}

function checkPath() {
  if [[ -e "$1" ]]; then
    if [[ -d "$1" ]]; then
      echo -e "找到指定路径$1"
    else
      echo -e "指定路径$1不是文件夹，已退出"
      exit $err_file
    fi
  else
    mkdir -p "$1"
    echo -e "\n已创建$1\n"
  fi
}

function checkCommand() {
  if command -v "$1" &> /dev/null; then
    return $normal
  else
    return $err_no_program
  fi
}

function cloneRepo() {
  checkPath "$path"
  if checkCommand "git"; then
    # 检测path下是否存在repo同名文件
    exist=()  # 不存在同名文件的
    nexist=() # 存在同名文件的
    for repo in ${repos[*]}; do
      if [[ ! -e "$path/$repo" ]]; then
        exist+=("$repo")
      else
        nexist+=("$repo")
      fi
    done

    # 操作不存在同名文件的repo
    for e_repo in ${exist[*]}; do
      echo -e "\n正在克隆$repo"
      git clone --recurse-submodules git@github.com:YHYJ/"$e_repo".git "$path/$e_repo"
    done

    # 操作存在同名文件的repo
    echo -e ""
    for ne_repo in ${nexist[*]}; do
      printf "同名文件\033[37m%-s\033[0m已存在，不克隆该仓库\n" "$ne_repo"
    done
  else
    echo -e "git 未安装，无法克隆"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  checkUser "root"
  cloneRepo
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_param
        ;;
    esac
  done
fi
