#!/usr/bin/env bash

: << !
Name: configure-tags
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 10:38:44

Description: 为指定文件夹下的子文件夹配置 Tag
- 只使用 -f/--folder 参数指定文件夹：
  - 如果该文件夹的子文件夹里有 .git 文件夹，则为子文件夹创建 Tag = 'repo'
  - 如果该文件夹的子文件夹没有 .git 文件夹，则为子文件夹创建 Tag = '<全小写子文件夹名>'
- -f/--folder 和 -t/--tag 参数配合使用：
  - -t/--tag 参数值为0，则 Tag = '<全小写子文件夹名>'"
  - -t/--tag 参数值为其他，则 Tag = '<-t/--tag 参数值>'"

Attentions:
-

Depends:
- dtags
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.1.5
readonly minor_version=20240426
readonly rel_version=3

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_file=1         # 文件/路径类错误
readonly err_permission=110 # 权限错误
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="configure tags for subfolders under the specified folder"
# path variable
readonly dtags_path="/usr/bin/dtags-activate"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m \x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -f, --folder      Configure the subfolders of this folder"
  echo -e "     -t, --tag         Specify Tags, one at a time"
  echo -e ""
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
  echo -e ""
  echo -e "Notice:"
  echo -e "    - Just use the -f/--folder parameter:"
  echo -e "      1. The subfolder under the folder specified by the -f/--folder parameter contains the .git folder, Tag = 'repo'"
  echo -e "      2. The subfolder under the folder specified by the -f/--folder parameter does not contain the .git folder, Tag = '<all lowercase subfolder name>'"
  echo -e "    - Just use the -t/--tag parameter:"
  echo -e "      1. -t/--tag parameter value is 0, Tag = '<all lowercase subfolder name>'"
  echo -e "      2. -t/--tag parameter value is other, Tag = '<-t/--tag parameter value>'"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function askQuestion() {
  while true; do
    read -e -r -p "$1"
    REPLY=${REPLY:-N}
    echo
    if [[ "$REPLY" =~ ^[Yy] ]]; then
      return 0
    elif [[ "$REPLY" =~ ^[Nn] ]]; then
      return 1
    else
      echo -e "Please input [Y/y] or [N/n]\n"
    fi
  done
}

function checkUser() {
  if [[ $USER == "$1" ]]; then
    echo -e "\n\x1b[31m[✘]\x1b[0m Current user is $1, refusal to execute"
    exit $err_permission
  fi
}

function addTags() {
  num=0
  if [[ -d "$target_folder" ]]; then
    for folder in "$target_folder"/*; do
      if [[ -d "$folder" ]]; then
        if [[ "$tagname" == 0 ]]; then
          tag=$(basename "$folder" | tr '[:upper:]' '[:lower:]')
          tag -y "$folder" -t "$tag"
        elif [ "$tagname" ]; then
          tag -y "$folder" -t "$tagname"
        elif [[ -d "$folder/.git" ]]; then
          tag -y "$folder" -t "repo"
        else
          tag=$(basename "$folder" | tr '[:upper:]' '[:lower:]')
          tag -y "$folder" -t "$tag"
        fi
        ((num++))
      elif [[ -f "$folder" ]]; then
        echo -e "$folder is a text file, ignore"
      else
        echo -e "$folder unknown file type, ignore"
      fi
      echo -e ""
    done
  else
    echo -e "\n\x1b[31mPath $target_folder does not exist\x1b[0m"
    exit $err_file
  fi

  echo -e "\x1b[34mA total of \x1b[0m\x1b[32m$num\x1b[0m\x1b[34m tags have been created/exist\x1b[0m"
  exit $normal
}

function main() {
  checkUser "root"

  if [[ -x "$dtags_path" ]]; then
    addTags
  else
    echo -e "Please install 'dtags' first"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "f:t:hv" --longoptions "folder:,tag:,help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case $1 in
      -f | --folder)
        target_folder=$2
        shift 2
        if [[ ${#@} -le 1 ]]; then
          main
        fi
        ;;
      -t | --tag)
        tagname=$2
        shift 2
        if [[ ${#@} -le 1 ]]; then
          main
        fi
        ;;
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
