#!/usr/bin/env bash

: << !
Name: get-vim-hotkey-doc
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2021-06-11 17:06:32

Description: 提取vim快捷键文档

Attentions:
-

Depends:
-

TODO:
- 尚未完善参数识别
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=0.2.3
readonly minor_version=20230213
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0        # 一切正常
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于提取vim快捷键说明以生成文档"

# path variable
readonly conf_file="$HOME/.space-vim/private/config.vim"
readonly doc_file="$HOME/.cache/SpiderData/App/vim/Vim-Hotkey.md"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e ""
  echo -e "     -h, --help        显示帮助信息"
  echo -e "     -v, --version     显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}
#------------------------- Feature Function
function main() {
  # 提取快捷键说明
  grep -r 'Hotkey' "$conf_file" > "$doc_file"
  # 格式化文档
  sed -i 's/--/|/g' "$doc_file" # 替换'--'为'|'
  sed -i 's/^"//' "$doc_file"   # 删除行首的'"'
  sed -i 's/^/|/' "$doc_file"   # 在行首添加'|'
  sed -i 's/$/|/' "$doc_file"   # 在行尾添加'|'
  # 添加文件头
  line1='|	关键字	|	归属	|	快捷键	|	说明	|'
  line2='|---|---|---|---'
  sed -i "1i\\$line2" "$doc_file"
  sed -i "1i\\$line1" "$doc_file"
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
if [[ ${#@} -lt 1 ]]; then
  main
else
  case $1 in
    -h | --help)
      helpInfo
      exit $normal
      ;;
    -v | --version)
      versionInfo
      exit $normal
      ;;
    *)
      helpInfo
      exit $err_unknown
      ;;
  esac
fi
