#!/usr/bin/env bash

: << !
Name: lock-screen
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:22:51

Description: Lock screen -- 锁屏程序

Attentions:
- 十六进制值：FF   F2  E6  D9  CC  BF  B3  A6  99  8C  80  73  66  59  4D  40  33  26  1A  0D  00
- 不透明度值：100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15  10  5   0

Depends:
- i3lock-color
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.1.2
readonly minor_version=20230213
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常

#------------------------- Parameter Variable
# description variable
readonly desc="用于锁定/解锁屏幕"

#------------------------- Parameter Variable
# color variable
readonly color_time='#000000BF'         # 黑色     75%不透明度
readonly color_date='#000000B3'         # 黑色     70%不透明度
readonly color_key_layout='#00000080'   # 黑色     50%不透明度
readonly color_inside='#0000001A'       # 黑色     10%不透明度
readonly color_line='#FFFFFF00'         # 纯白     0%不透明度
readonly color_inside_ver='#FFFAF099'   # 白色     60%不透明度
readonly color_inside_wrong='#FFF0F580' # 紫罗兰红 50%不透明度
readonly color_ring='#C0C0C0FF'         # 银白色   100%不透明度
readonly color_separator='#00BFFFFF'    # 深天蓝   100%不透明度
readonly color_ring_ver='#FFFFFFFF'     # 纯白     100%不透明度
readonly color_ring_wrong='#00000033'   # 黑色     20%不透明度
readonly color_keyhl='#696969FF'        # 暗灰色   100%不透明度
readonly color_bshl='#87CEFAFF'         # 淡蓝色   100%不透明度
readonly color_verif='#40E0D0FF'        # 黑色     100%不透明度
readonly color_wrong='#FF0000FF'        # 纯红     100%不透明度
# path variable
readonly image_path="$HOME/Pictures/Wallpapers"
# time variable
readonly time_str='%H:%M:%S'
readonly date_str='%Y.%m.%d %A'
# ring variable
readonly screen=0
readonly keylayout=0
readonly veriftext='正在解锁'
readonly wrongtext='密码错误'
readonly noinputtext='输入为空'
readonly locktext='已锁屏'
readonly lockfailedtext='锁屏失败'
readonly radius=90
readonly ring_width=2.0

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name OPTIONS"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function i3Lock() {
  if [ -f "$image_path/$1" ]; then
    i3lock \
      --clock \
      --image="$image_path/$1" \
      --screen="$screen" \
      --time-str="$time_str" \
      --date-str="$date_str" \
      --keylayout="$keylayout" \
      --time-color=$color_time \
      --date-color=$color_date \
      --layout-color=$color_key_layout \
      --line-color=$color_line \
      --inside-color=$color_inside \
      --insidever-color=$color_inside_ver \
      --insidewrong-color=$color_inside_wrong \
      --ring-color=$color_ring \
      --ringver-color=$color_ring_ver \
      --ringwrong-color=$color_ring_wrong \
      --separator-color=$color_separator \
      --keyhl-color=$color_keyhl \
      --bshl-color=$color_bshl \
      --verif-color=$color_verif \
      --wrong-color=$color_wrong \
      --verif-text="$veriftext" \
      --wrong-text="$wrongtext" \
      --noinput-text="$noinputtext" \
      --lock-text="$locktext" \
      --lockfailed-text="$lockfailedtext" \
      --radius="$radius" \
      --ring-width="$ring_width" \
      --ignore-empty-password \
      --show-failed-attempts
  else
    notify-send --urgency=normal --icon=system-lock-screen --app-name='Lock Screen' "屏幕锁定" "指定锁屏壁纸不存在"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
case $1 in
  -h | --help)
    helpInfo
    exit $normal
    ;;
  -v | --version)
    versionInfo
    exit $normal
    ;;
  *)
    i3Lock "$1"
    exit $normal
    ;;
esac
