#!/usr/bin/env bash

: << !
Name: open
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:51:05

Description: 自动识别 URL 类型并以默认程序打开

Attentions:
-

Depends:
- xdg-utils
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.4.1
readonly minor_version=20240524
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0 # 一切正常

#------------------------- Parameter Variable
# description variable
readonly desc="automatically recognize URL type and open with default program"

# command
open="xdg-open"
editor="nano"
catimg="feh"
player="mpv"

# unable to open file
declare -a failed_files

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m \x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function checkCommand() {
  # 确定编辑器
  if command -v nvim &> /dev/null; then
    editor="nvim"
  elif command -v vim &> /dev/null; then
    editor="vim"
  elif command -v vi &> /dev/null; then
    editor="vi"
  fi

  # 确定图片查看器
  if command -v gwenview &> /dev/null; then # KDE Plasma
    catimg="gwenview"
  elif command -v eog &> /dev/null; then # GNOME
    catimg="eog"
  elif command -v ristretto &> /dev/null; then # XFCE
    catimg="ristretto"
  elif command -v sxiv &> /dev/null; then
    catimg="sxiv"
  elif command -v imv &> /dev/null; then
    catimg="imv"
  fi

  # 确定视频播放器
  if command -v dragon &> /dev/null; then # KDE Plasma
    player="dragon"
  elif command -v totem &> /dev/null; then # GNOME
    player="totem"
  elif command -v ristretto &> /dev/null; then # XFCE
    player="ristretto"
  elif command -v vlc &> /dev/null; then
    player="vlc"
  fi
}

function echoFailedFiles() {
  # 输出无法打开的文件的信息
  if [ ${#failed_files[@]} -ne 0 ]; then
    for failed_file in "${failed_files[@]}"; do
      echo -e "Can not open: $failed_file"
    done
  fi
}

function main() {
  checkCommand

  # 文件集中到变量中统一打开
  local texts=()
  local pictures=()
  local videos=()

  for url in "$@"; do
    if [[ -d $url ]]; then # 文件夹
      $open "$url" > /dev/null 2>&1
    elif [[ -f $url ]]; then # 文件
      # 判断文件类型
      file_type=$(file -b --mime-type "$url")
      if [[ "$file_type" == text/* ]]; then # 普通文本文件
        texts+=("$url")
      elif [[ "$file_type" == image/* ]]; then # 图片
        pictures+=("$url")
      elif [[ "$file_type" == video/* ]]; then # 视频
        videos+=("$url")
      else
        $open "$url" > /dev/null 2>&1
      fi
    elif [[ "$url" == file://* ]]; then  # file://*
      if [[ -d "${url#file://}" ]]; then # 文件夹
        $open "$url" > /dev/null 2>&1
      elif [[ -f "${url#file://}" ]]; then # 文件
        # 判断文件类型
        file_type=$(file -b --mime-type "${url#file://}")
        if [[ "$file_type" == text/* ]]; then # 普通文本文件
          texts+=("$url")
        elif [[ "$file_type" == image/* ]]; then # 图片
          pictures+=("$url")
        elif [[ "$file_type" == video/* ]]; then # 视频
          videos+=("$url")
        else
          $open "$url" > /dev/null 2>&1
        fi
      else
        # 将无法打开的文件名添加到数组中
        failed_files+=("$file")
      fi
    elif [[ "$url" == http://* || "$url" == https://* || "$url" == mailto:* || "$url" == tel:* ]]; then # URL
      $open "$url" > /dev/null 2>&1
    else
      # 将无法打开的文件名添加到数组中
      failed_files+=("$file")
    fi
  done

  # 打开普通文本文件
  if [ ${#texts[@]} -gt 0 ]; then
    $editor "${texts[@]}"
  fi

  # 打开图片
  if [ ${#pictures[@]} -gt 0 ]; then
    $catimg "${pictures[@]}" > /dev/null 2>&1 &
  fi

  # 打开视频
  if [ ${#videos[@]} -gt 0 ]; then
    $player "${videos[@]}" > /dev/null 2>&1 &
  fi

}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  main "$PWD"
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        exit $normal
        ;;
      -v | --version)
        versionInfo
        exit $normal
        ;;
      --)
        shift 1
        ;;
      *)
        main "$@"
        echoFailedFiles
        exit $normal
        ;;
    esac
  done
fi
