#!/usr/bin/env bash

: << !
Name: open
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:51:05

Description: 自动识别 URI 类型并以默认程序打开

Attentions:
-

Depends:
- xdg-utils
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.4.0
readonly minor_version=20240524
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0 # 一切正常

#------------------------- Parameter Variable
# description variable
readonly desc="automatically recognize URI type and open with default program"

# command
open="xdg-open"
editor="nano"

# Unable to open file
declare -a failed_files

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m \x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function checkCommand() {
  # 确定编辑器
  if command -v nvim &> /dev/null; then
    editor="nvim"
  elif command -v vim &> /dev/null; then
    editor="vim"
  elif command -v vi &> /dev/null; then
    editor="vi"
  fi
}

function echoFailedFiles() {
  # 输出无法打开的文件的信息
  if [ ${#failed_files[@]} -ne 0 ]; then
    for failed_file in "${failed_files[@]}"; do
      echo -e "Can not open: $failed_file"
    done
  fi
}

function main() {
  checkCommand

  # 文件集中到变量中统一打开
  local texts=()

  for uri in "$@"; do
    if [[ -d $uri ]]; then # 文件夹
      $open "$uri" > /dev/null 2>&1
    elif [[ -f $uri ]]; then # 文件
      # 判断文件类型
      file_type=$(file -b --mime-type "$uri")
      if [[ "$file_type" == text/* ]]; then # 普通文本文件
        texts+=("$uri")
      else
        $open "$uri" > /dev/null 2>&1
      fi
    elif [[ "$uri" == file://* ]]; then # URL
      if [[ -d "${uri#file://}" ]]; then
        $open "$uri" > /dev/null 2>&1
      elif [[ -f "${uri#file://}" ]]; then
        texts+=("$uri")
      else
        # 将无法打开的文件名添加到数组中
        failed_files+=("$file")
      fi
    elif [[ "$uri" == http://* || "$uri" == https://* || "$uri" == mailto:* || "$uri" == tel:* ]]; then # URL
      $open "$uri" > /dev/null 2>&1
    else
      # 将无法打开的文件名添加到数组中
      failed_files+=("$file")
    fi
  done

  if [ ${#texts[@]} -gt 0 ]; then
    $editor "${texts[@]}"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  main "$PWD"
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        exit $normal
        ;;
      -v | --version)
        versionInfo
        exit $normal
        ;;
      --)
        shift 1
        ;;
      *)
        main "$@"
        echoFailedFiles
        exit $normal
        ;;
    esac
  done
fi
