#!/usr/bin/env bash

: << !
Name: polybar-script_trash
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-05-30 21:00:27

Description: 操作回收站

Attentions:
- 根据参数确定操作

Depends:
- findutils
- libnotify
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=2.1.4
readonly minor_version=20230213
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0    # 一切正常
readonly err_param=2 # 参数错误

#------------------------- Parameter Variable
# description variable
readonly desc="是Polybar的脚本，用于操作回收站文件"

# path variable
readonly trash_path="$HOME/.local/share/Trash/files"
# count variable
number=$(find "$trash_path" -maxdepth 1 | wc -l)
readonly number
readonly real_number=$((number - 1))

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -n, --number      回收站文件计数"
  echo -e "     -l, --list        列出回收站文件"
  echo -e "     -e, --empty       清空回收站"
  echo -e ""
  echo -e "     -h, --help        显示帮助信息"
  echo -e "     -v, --version     显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function number() {
  #function_body
  if [[ $real_number != 0 ]]; then
    echo "$real_number"
  else
    echo ""
  fi
  exit $normal
}

function listFile() {
  notify-send --urgency=normal --icon=trashindicator --app-name='Trash info' "回收站文件" "$(ls -A "$trash_path")"
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
case $1 in
  -n | --number)
    number
    ;;
  -l | --list)
    listFile
    exit $normal
    ;;
  -e | --empty)
    /usr/local/bin/trash-empty_substitute --force
    exit $normal
    ;;
  -h | --help)
    helpInfo
    exit $normal
    ;;
  -v | --version)
    versionInfo
    exit $normal
    ;;
  *)
    exit $err_param
    ;;
esac
