#!/usr/bin/env bash

: << !
Name: polybar-script_redshift-info
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:25:28

Description: 获取色温信息

Attentions:
-

Depends:
- grep
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=2.1.2
readonly minor_version=20230213
readonly rel_version=1

#------------------------- Exit Code Variable
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="是Polybar的脚本，用于获取色温信息"
# language variable
if [[ $LANG == 'zh_CN.UTF-8' ]]; then
  color_temp='色温'
else
  color_temp='temp'
fi

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help        显示帮助信息"
  echo -e "     -v, --version     显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function main() {
  if [ "$(pgrep -x redshift)" ]; then
    temp=$(redshift -p 2> /dev/null | grep "$color_temp" | cut -d ":" -f 2 | tr -dc "[:digit:]")

    if [ -z "$temp" ]; then
      echo "%{F#65737E}"
    elif [ "$temp" -ge 5000 ]; then
      echo "%{F#8FA1B3}"
    elif [ "$temp" -ge 4000 ]; then
      echo "%{F#EBCB8B}"
    else
      echo "%{F#D08770}"
    fi
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
