#!/usr/bin/env bash

: << !
Name: pre-trash-empty
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2022-05-17 10:05:57

Description: 执行trash-empty命令前防止不经确认直接清空回收站文件

Attentions:
-

Depends:
-
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=0.1.1
readonly minor_version=20230316
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_no_program=127 # 未找到命令
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="执行trash-empty前的确认"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -f, --force       是否强制清空回收站"
  echo -e ""
  echo -e "     -h, --help        显示帮助信息"
  echo -e "     -v, --version     显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

function askQuestion() {
  while true; do
    read -e -r -p "$1"
    REPLY=${REPLY:-N}
    echo
    if [[ "$REPLY" =~ ^[Yy] ]]; then
      return 0
    elif [[ "$REPLY" =~ ^[Nn] ]]; then
      return 1
    else
      echo -e "应输入 Y/y 或 N/n\n"
    fi
  done
}

#------------------------- Feature Function
function checkCommand() {
  if command -v "$1" &> /dev/null; then
    return $normal
  else
    return $err_no_program
  fi
}

function removeFile() {
  if [[ -n $DISPLAY ]]; then
    if checkCommand "zenity"; then
      zenity --question --default-cancel --text="是否确认移除回收站中的所有项目\n（这些项目将永远消失）"
    else
      askQuestion "是否确认移除回收站中的所有项目（这些项目将永远消失）[y/N]: "
    fi
  else
    askQuestion "是否确认移除回收站中的所有项目（这些项目将永远消失）[y/N]: "
  fi
  status=$?
  if [[ $status == 0 ]]; then
    if [[ -n $1 ]]; then
      /usr/bin/trash-empty -f
    else
      /usr/bin/trash-empty
    fi
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "fhv" --longoptions "force,help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case $1 in
      -f | --force)
        removeFile "$1"
        shift 1
        ;;
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
