#!/usr/bin/env bash

: <<!
Name: py-virtualenv-tool
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2023-02-09 11:00:29

Description: 用于操作 Python Virtualenv 环境的备份、创建和备份文件删除

Attentions:
-

Depends:
-
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# Program name
NAME=$(basename "${0}")
readonly NAME
# Program description
readonly DESC="backup, creation, and backup file deletion for operating Python Virtualenv environments"
# Program version
readonly MAJOR=0.1.6
readonly MINOR=20240704
readonly RELEASE=1

#------------------------- Exit Code Variable
readonly NORMAL=0           # 一切正常
readonly ERR_FILE=1         # 文件/路径类错误
readonly ERR_NO_PROGRAM=127 # 未找到命令
readonly ERR_UNKNOWN=255    # 未知错误

#------------------------- Other Variable
# Environment
readonly STORAGE="$HOME/.cache/SpiderData"
readonly VIRTUALENV_DIR="$STORAGE/App/virtualenv"
# App
PIP="pip"
VIRTUALENVWRAPPER="/usr/bin/virtualenvwrapper.sh"
VIRTUALENVWRAPPER_LAZY="/usr/bin/virtualenvwrapper_lazy.sh"
# Print
readonly SPACE='    '

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m${NAME}\x1b[0m \x1b[1m${DESC}\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     ${NAME} [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -d, --delete      Delete virtual environment backup files"
  echo -e "     -m, --make        Use files to build a virtual environment"
  echo -e "     -s, --save        Save virtual environment backup file"
  echo -e ""
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m${NAME}\x1b[0m version (\x1b[1m${MAJOR}-${MINOR}.${RELEASE}\x1b[0m)"
}

#------------------------- Feature Function
function checkOS() {
  # 检测系统类型，确定因系统差异导致的变量或命令不同
  if [[ "${OSTYPE}" == "darwin"* ]]; then
    PIP="pip3.11"
    VIRTUALENVWRAPPER="/opt/homebrew/bin/virtualenvwrapper.sh"
    VIRTUALENVWRAPPER_LAZY="/opt/homebrew/bin/virtualenvwrapper_lazy.sh"
  elif [[ "${OSTYPE}" == "linux-gnu"* ]]; then
    PIP="pip"
    VIRTUALENVWRAPPER="/usr/bin/virtualenvwrapper.sh"
    VIRTUALENVWRAPPER_LAZY="/usr/bin/virtualenvwrapper_lazy.sh"
  fi
}

function initVirtualenv() {
  if [ -s "${VIRTUALENVWRAPPER_LAZY}" ]; then
    # shellcheck source=/dev/null
    source "${VIRTUALENVWRAPPER_LAZY}"
  elif [ -s "${VIRTUALENVWRAPPER}" ]; then
    # shellcheck source=/dev/null
    source "${VIRTUALENVWRAPPER}"
  else
    echo -e "Please install 'virtualenv' and 'virtualenvwrapper' first"
    exit ${ERR_NO_PROGRAM}
  fi
  venvs=$(lsvirtualenv -b)
}

function checkPath() {
  if [[ -e "${1}" ]]; then
    if [[ ! -d "${1}" ]]; then
      echo -e "Path '${1}' is not a folder, exit"
      exit ${ERR_FILE}
    fi
  else
    mkdir -p "${1}"
  fi
}

function checkCommand() {
  if command -v "${1}" >/dev/null 2>&1; then
    return ${NORMAL}
  else
    return ${ERR_NO_PROGRAM}
  fi
}

function deleteVirtualenvFile() {
  # 删除虚拟环境备份文件
  rm -rf "${VIRTUALENV_DIR:?}/"*
}

function saveVirtualenv() {
  if checkCommand "${PIP}"; then
    printf "%s %-14s \x1b[36m%s\x1b[0m %s\n" "${SPACE}" "Python-Venv" "-->" "${VIRTUALENV_DIR}/*"
    for venv in ${venvs[*]}; do
      workon "${venv}"
      filepath="${VIRTUALENV_DIR}"/requirements_"${venv}".txt
      pip freeze >"${filepath}"
      printf "%s%s Venv: \x1b[35m%2s\x1b[0m \x1b[37m%s\x1b[0m\n" "${SPACE}" "${SPACE}" "✔" "${venv}"
    done
  else
    echo -e "Please install 'pip' first"
  fi
}

function makeVirtualenv() {
  if checkCommand "${PIP}"; then
    # 遍历存储的requirements*.txt，得到绝对路径表示的文件名
    if [ "$(ls -A "${VIRTUALENV_DIR}")" ]; then
      for filepath in "${VIRTUALENV_DIR}"/*.txt; do
        # 获取文件名并切分得到虚拟环境名
        filename=$(basename "${filepath}")
        envname=$(echo "${filename}" | cut -d "_" -f 2 | cut -d "." -f 1)
        echo -e "\x1b[1m--> Make virtual environment: \x1b[32m${envname}\x1b[0m\x1b[0m"
        # 将切分得到的虚拟环境名和现有虚拟环境名做对比
        if [[ ! ${venvs} =~ (^|[[:space:]])${envname}($|[[:space:]]) ]]; then
          # 名字不同则创建并搭建环境
          mkvirtualenv -p python3 "${envname}"
          workon "${envname}"
          echo -e "\x1b[1m--> Install requirements\x1b[0m"
          pip install -r "${filepath}"
        fi
        echo -e "\x1b[1mDone\x1b[0m\n"
      done
    fi
  else
    echo -e "Please install 'pip' first"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
checkOS
initVirtualenv
mkdir -p "${VIRTUALENV_DIR}"

ARGS=$(getopt --options "dsmhv" --longoptions "delete,save,make,help,version" -n "${NAME}" -- "${@}")
eval set -- "${ARGS}"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    checkPath "${VIRTUALENV_DIR}"
    case ${1} in
    -d | --delete)
      deleteVirtualenvFile
      shift 1
      ;;
    -s | --save)
      saveVirtualenv
      shift 1
      ;;
    -m | --make)
      makeVirtualenv
      shift 1
      ;;
    -h | --help)
      helpInfo
      shift 1
      ;;
    -v | --version)
      versionInfo
      shift 1
      ;;
    --)
      shift 1
      break
      ;;
    *)
      helpInfo
      exit ${ERR_UNKNOWN}
      ;;
    esac
  done
fi
