#!/usr/bin/env bash

: << !
Name: save-docker-images
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:47:18

Description: 是 Linux 系统用来备份 Docker 镜像的工具

Attentions:
- 0. 进行权限认证
- 1. 判断是否能够取得存储路径参数：能——使用该参数；不能——使用默认存储路径
- 2. 判断参数类型：空文件/非空文件/文件夹/字符串，分别返回不同值
- 3. 根据返回值进行具体操作

Depends:
- systemd
- docker
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=1.1.4
readonly minor_version=20240426
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_file=1         # 文件/路径类错误
readonly err_param=2        # 参数错误
readonly err_permission=110 # 权限错误
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="is a tool used by Linux to back up Docker images"

# path variable
readonly images_savefile="$HOME/Documents/LocalBackups/docker/Mydocker.images"
# detection variable
group_docker=$(grep -E 'docker' /etc/group)
readonly group_docker
# time variable
readonly time_out=60

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m \x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "\x1b[1;33m默认备份路径\x1b[0m: \x1b[34m$images_savefile\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "options:"
  echo -e "     /path/to/save.file      Specify the path to save the backup file"
  echo -e ""
  echo -e "     -h, --help              Show help information"
  echo -e "     -v, --version           Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function checkPath() {
  if [[ -e "$1" ]]; then
    if [[ ! -d "$1" ]]; then
      echo -e "Path '$1' is not a folder, exit"
      exit $err_file
    fi
  else
    mkdir -p "$1"
  fi
}

function userAuthentication() {
  # 权限认证
  if [[ -n $group_docker ]]; then
    # 有'docker'组
    if [[ $group_docker =~ $USER ]]; then
      # 当前用户在'docker'组
      return 0
    else
      # 当前用户不在'docker'组
      echo -e "\x1b[31m[✘]\x1b[0m User '$USER' is not a member of the '$group_docker' group. Please add it to the '$group_docker' group and try again"
      return 2
    fi
  else
    # 没有'docker'组
    echo -e "\x1b[31m[✘]\x1b[0m The '$group_docker' group does not exist. Please create it and add $USER to the group and try again"
    return 1
  fi
}

function saveImage() {
  # 备份images
  if systemctl is-active docker &> /dev/null; then
    docker save $(docker images --format '{{.Repository}}') -o "$1" # 不要使用引号
  else
    echo -e "\x1b[31m[✘]\x1b[0m The docker service has not started, please try again after starting"
  fi
}

function getFilename() {
  # 分解路径字符串得到基础文件名
  case "$1" in
    --help | -h | help | h)
      parameterType "$1"
      ;;
    *)
      filename="$(basename "$1")"
      ;;
  esac
}

function getDirname() {
  # 分解路径字符串得到文件夹名
  dirname="$(dirname "$1")"
}

function nonEmptyFile() {
  # 非空文件覆写提示
  echo -e "$1 file is not empty"
}

function askQuestion() {
  # 用户进行确认
  while true; do
    read -e -t "$time_out" -r -p "$1"
    REPLY=${REPLY:-N}
    echo -e ""
    if [[ "$REPLY" =~ ^[Yy] ]]; then
      return 0
    elif [[ "$REPLY" =~ ^[Nn] ]]; then
      return 1
    else
      echo -e "Please input [Y/y] or [N/n]\n"
    fi
  done
}

function parameterType() {
  # 判断参数类型：空文件/非空文件/文件夹/字符串
  # return param_type：空文件=100 / 非空文件=101 / 文件夹=102 / 字符串=103
  parameter="$1"
  if [[ $parameter == 'help' ]] || [[ $parameter == '--help' ]] || [[ $parameter == 'h' ]] || [[ $parameter == '-h' ]]; then
    return 103
  elif [[ ! -e $parameter ]] || [[ ! -s $parameter ]]; then # 文件不存在或者存在但大小为0
    return 100
  elif [[ -s $parameter ]]; then # 非空文件
    return 101
  elif [[ -d $parameter ]]; then # 文件夹
    return 102
  else # 其他，一般是字符串
    return 255
  fi
}

function exitProgram() {
  # 退出
  echo -e "$1"
  exit "$2"
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
if userAuthentication; then
  if [[ -n $1 ]]; then # 给定一个参数
    getFilename "$1"   # return filename
    parameterType "$1" # case 行到本行之间不能有其他代码
    case $? in
      100) # 参数是一个空文件
        echo -e "Backup files are stored at: $1\n"
        echo -e "The backup file name is: $filename\n"
        if askQuestion "Confirm backup [y/N]: "; then
          checkPath "$dirname"
          echo -e "Backing up the Docker image, please wait..."
          saveImage "$1"
        else
          exitProgram "Exit" $normal
        fi
        ;;
      101) # 参数是一个非空文件
        echo -e "Backup files are stored at: $1\n"
        echo -e "The backup file name is: $filename\n"
        nonEmptyFile "$filename" # 非空文件覆写提示
        if askQuestion "Confirm to overwrite (original backup file content will be lost) [y/N]: "; then
          echo -e "Backing up the Docker image, please wait..."
          saveImage "$1"
        else
          exitProgram "Exit" $normal
        fi
        ;;
      102) # 参数是一个文件夹
        exitProgram "The parameter is a folder, please pass the file as the parameter" $err_param
        ;;
      103) # 参数是一个字符串
        case $1 in
          -h | --help)
            helpInfo
            exit $normal
            ;;
          -v | --version)
            versionInfo
            exit $normal
            ;;
          *)
            helpInfo
            exitProgram "\n\nUse the help parameter to view help information" $err_unknown
            ;;
        esac
        ;;
      *)
        helpInfo
        exitProgram "\n\nUse the help parameter to view help information" $err_unknown
        ;;
    esac
  else                             # 没有指定备份文件存储位置，使用默认值
    getDirname "$images_savefile"  # return dirname
    getFilename "$images_savefile" # return filename
    echo -e "No storage path is given, use default value: $images_savefile"
    echo -e "The backup file name is: $filename\n"
    if [[ ! -s $images_savefile ]]; then # 默认文件是一个空文件
      if askQuestion "Confirm backup [y/N]: "; then
        checkPath "$dirname"
        echo -e "Backing up the Docker image, please wait..."
        saveImage "$images_savefile"
      else
        exitProgram "Exit" $normal
      fi
    elif [[ -d $images_savefile ]]; then # 默认参数是一个文件夹（一般情况不会出现）
      exitProgram "The parameter is a folder, please pass the file as the parameter" $err_param
    elif [[ -s $images_savefile ]]; then # 默认文件是一个非空文件
      nonEmptyFile "$filename"           # 非空文件覆写提示
      if askQuestion "Confirm to overwrite (original backup file content will be lost) [y/N]: "; then
        echo -e "Backing up the Docker image, please wait..."
        saveImage "$images_savefile"
      else
        exitProgram "Exit" $normal
      fi
    fi
  fi
else
  exitProgram "Permission authentication failed" $err_permission
fi
