#!/usr/bin/env bash

: << !
Name: scleaner
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:52:22

Description: System cleaner -- 系统清洁器

Attentions:
- lonely_pkgs变量不能加引号

Depends:
- pacman
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Parameter Variable
# detection variable
lonely_pkgs=$(pacman -Qtdq)
readonly lonely_pkgs

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
if [[ -z $lonely_pkgs ]]; then
  echo -e "\\e[35m[✔]\\e[0m 没有需要清理的包"
  repo-elephant
else
  pacman -Rn $lonely_pkgs # 不能使用引号
fi
