#!/usr/bin/env bash

: << !
Name: sfm
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:51:05

Description: Start file manager -- 在指定目录启动文件管理器

Attentions:
-

Depends:
- xdg-utils
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.2.6
readonly minor_version=20230316
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_no_program=127 # 未找到命令

#------------------------- Parameter Variable
# description variable
readonly desc="在指定路径启动文件管理器"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function checkCommand() {
  if command -v "$1" > /dev/null 2>&1; then
    return $normal
  else
    return $err_no_program
  fi
}

function getArgType() {
  if checkCommand "xdg-open"; then
    if [[ -d $1 ]]; then
      xdg-open "$1" &> /dev/null &
      exit $normal
    else
      xdg-open . &> /dev/null &
      exit $normal
    fi
  else
    echo -e "xdg-open 未安装"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
case $1 in
  -h | --help)
    helpInfo
    ;;
  -v | --version)
    versionInfo
    ;;
  *)
    getArgType "$1"
    ;;
esac
