#!/usr/bin/env bash

: <<!
Name: spacevim-update
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2022-06-11 16:43:34

Description: 用于更新手动安装的 space-vim

Attentions:
-

Depends:
- make
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# Program name
NAME=$(basename "${0}")
readonly NAME
# Program description
readonly DESC="update manually installed space-vim"
# Program version
readonly MAJOR=0.1.2
readonly MINOR=20240704
readonly RELEASE=1

#------------------------- Exit Code Variable
readonly NORMAL=0           # 一切正常
readonly ERR_FILE=1         # 文件/路径类错误
readonly ERR_NO_PROGRAM=127 # 未找到命令
readonly ERR_UNKNOWN=255    # 未知错误

#------------------------- Other Variable
# Path
readonly INSTALL_PATH="${HOME}/.space-vim"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m${NAME}\x1b[0m \x1b[1m${DESC}\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     ${NAME} [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m${NAME}\x1b[0m version (\x1b[1m${MAJOR}-${MINOR}.${RELEASE}\x1b[0m)"
}

#------------------------- Feature Function
function checkPath() {
  if [[ -e "${1}" ]]; then
    if [[ ! -d "${1}" ]]; then
      echo -e "Path '${1}' is not a folder, exit"
      exit ${ERR_FILE}
    fi
  else
    mkdir -p "${1}"
  fi
}

function checkCommand() {
  if command -v "${1}" >/dev/null 2>&1; then
    return ${NORMAL}
  else
    return ${ERR_NO_PROGRAM}
  fi
}

function makeUpdate() {
  if checkCommand "make"; then
    current_path=$(pwd)
    cd "${INSTALL_PATH}" || exit ${ERR_FILE}
    make update
    cd "${current_path}" || exit ${ERR_FILE}
  else
    echo -e "Please install 'make' first"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "${NAME}" -- "${@}")
eval set -- "${ARGS}"

if [[ ${#@} -lt 2 ]]; then
  checkPath "${INSTALL_PATH}"
  makeUpdate
else
  while true; do
    case ${1} in
    -h | --help)
      helpInfo
      shift 1
      ;;
    -v | --version)
      versionInfo
      shift 1
      ;;
    --)
      shift 1
      break
      ;;
    *)
      helpInfo
      exit ${ERR_UNKNOWN}
      ;;
    esac
  done
fi
