#!/usr/bin/env bash

: << !
Name: spider
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2022-10-24 14:48:12

Description: Linux系统信息搜集工具

Attentions: 搜集如下信息
- Package
- Service
- User
- Vim
- Guake
- Virtualenv

Depends:
- coreutils
- diffutils/colordiff
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.2.0
readonly minor_version=20230306
readonly rel_version=2

#------------------------- Exit Code Variable
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于搜集Linux系统信息"

# 搜集结果存储路径
readonly datadir="$HOME/.cache/SpiderData"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "\033[1;33m搜集结果存储于\033[0m: \033[34m$datadir\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -g, --get [MODULE]    指定搜集的模块"
  echo -e ""
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
  echo -e ""
  echo -e "Modules:"
  echo -e "     all                   搜集全部模块"
  echo -e "     app                   搜集特定软件信息"
  echo -e "     env                   搜集开发工具虚拟环境信息"
  echo -e "     package               搜集安装包信息"
  echo -e "     service               搜集服务信息"
  echo -e "     user                  搜集用户信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

function finish() {
  echo -e "\n\033[35m[✔]\033[0m 信息搜集完成"
}

#------------------------- Feature Function
function Check() {
  if [[ ! -d $datadir ]]; then
    mkdir "$datadir"
  fi
}

function AppInfo() {
  echo -e "\033[1;34mApp\033[0m"
  /usr/local/bin/get-program-info --name all
}

function VirtualenvInfo() {
  echo -e "\033[1;34mVirtualenv\033[0m"
  /usr/local/bin/py-virtualenv-tool --save # Python Virtualenv
}

function PackageInfo() {
  echo -e "\033[1;34mPackage\033[0m"
  /usr/local/bin/get-system-info --name package # Package List
}

function ServiceInfo() {
  echo -e "\033[1;34mService\033[0m"
  /usr/local/bin/get-system-info --name service # Service List
}

function UserInfo() {
  echo -e "\033[1;34mUser\033[0m"
  /usr/local/bin/get-system-info --name user # User List
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "g:hv" --longoptions "get:,help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case $1 in
      -g | --get)
        case $2 in
          all)
            Check
            AppInfo
            PackageInfo
            ServiceInfo
            UserInfo
            VirtualenvInfo
            finish
            shift 1
            ;;
          app)
            Check
            AppInfo
            finish
            shift 1
            ;;
          env)
            Check
            VirtualenvInfo
            finish
            shift 1
            ;;
          package)
            Check
            PackageInfo
            finish
            shift 1
            ;;
          service)
            Check
            ServiceInfo
            finish
            shift 1
            ;;
          user)
            Check
            UserInfo
            finish
            shift 1
            ;;
          --)
            shift 1
            break
            ;;
          *)
            echo -e "\n\033[31m[✘]\033[0m 无法搜集该内容"
            ;;
        esac
        shift 1
        ;;
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
