#!/usr/bin/env bash

: <<!
Name: syncer
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2025-08-12 15:26:22

Description: 按系统分别备份其文件

Attentions:
-

Depends:
- rclone
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
NAME=$(basename "${0}")
STORAGE="YJ-NAS:System/${HOSTNAME}"
TRANSFER=8

#------------------------- Log Variable
LOGPATH="/home/${USER}/.local/share/logs/Syncer"
LOGNAME="${NAME}.log"
LOGFILE="${LOGPATH}/${LOGNAME}"
LOGLEVEL="WARNING"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

#------------------------- Sync Variable
# Docker
BASE_DOCKER="/home/${USER}/Documents"
DIRECTORY_DOCKER="Docker"
TARGETS_DOCKER=("Run" "Volume")

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Feature Function
# 日志函数
function logger() {
  local line

  # 无参数输出空行
  if [ $# -eq 0 ]; then
    # 无参数：输出一个空行
    printf '%b\n' ""
    printf '%s\n' "" >>"${LOGFILE}"
    return
  fi

  printf '%s\n' "${*}" | while IFS= read -r line; do
    # 控制台输出（解析 ANSI 转义）
    printf '%s %b\n' "${TIMESTAMP}" "${line}"
    # 日志输出（去除 ANSI 颜色代码）
    printf '%s %s\n' "${TIMESTAMP}" "${line}" | sed 's/\\x1b\[[0-9;]*[mGK]//g; s/\\033\[[0-9;]*[mGK]//g' >>"${LOGFILE}"
  done
}

function syncer() {
  local storage=${1}
  local base=${2}
  local directory=${3}
  shift 3
  local targets=("$@")

  for target in "${targets[@]}"; do
    source_path="${base}/${directory}/${target}" # 源路径

    if [ -e "${source_path}" ]; then
      # 源文件不存在
      logger "WARN  : 源文件 ${source_path} 不存在，跳过"
      continue
    elif [ -f "${source_path}" ]; then
      # 文件
      storage_path="${storage}/${directory}" # 最终备份路径
    elif [ -d "${source_path}" ]; then
      # 文件夹
      storage_path="${storage}/${directory}/${target}" # 最终备份路径
    else
      logger "ERROR : ${source_path} 不是文件或文件夹，跳过"
    fi

    logger "INFO  : 正在备份 ${source_path} -> ${storage_path}"

    # 执行备份
    rclone copy --update "${source_path}" "${storage_path}" --transfers=${TRANSFER} --log-file="${LOGFILE}" --log-level ${LOGLEVEL}

    # 检查状态
    STATUS=${?}
    if [ ${STATUS} -eq 0 ]; then
      logger "INFO  : 成功备份 ${source_path}"
    else
      logger "ERROR : 备份失败 ${source_path}, 错误代码 ${STATUS}"
    fi
  done
}
####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
# 确保日志目录存在
mkdir -p "${LOGPATH}"

# Docker
syncer "${STORAGE}" "${BASE_DOCKER}" "${DIRECTORY_DOCKER}" "${TARGETS_DOCKER[@]}"
