#!/usr/bin/env bash

: <<!
Name: syncer
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2025-08-12 15:26:22

Description: 按系统分别备份其文件

Attentions:
-

Depends:
- rclone
  - copy: 备份，目标端不删除源端已删除的文件
  - sync: 同步，使目标端完全成为源端的镜像
  - bisync: 双向同步，两端的变化都同步到对端
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# Program name
NAME=$(basename "${0}")
readonly NAME
# Program description
readonly DESC="back up files by system"
# Program nversion
readonly MAJOR=0.0.5
readonly MINOR=20250814
readonly RELEASE=1

#------------------------- Exit Code Variable
readonly ERR_FILE=1     # 文件/路径类错误
readonly ERR_PARAM=2    # 参数错误
readonly ERR_UKNOWN=255 # 未知错误

#------------------------- Rclone Variable
TRANSFER=8      # 并行传输任务数
RESOLVE="newer" # 文件冲突处理策略，可选："nonw"、"newer"、"older"、"larger"、"smaller" 等

#------------------------- Log Variable
LOGPATH="/home/${USER}/.local/share/logs/Syncer"
LOGNAME="${NAME}.log"
LOGFILE="${LOGPATH}/${LOGNAME}"
LOGLEVEL="WARNING"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

#------------------------- Sync Variable
# Docker
# -- 存储端
SYSTEM_STORAGE="YJ-NAS:System/${HOSTNAME}" # 目标存储地址
SYSTEM_STORAGE_TYPE="sync"                 # 同步类型，可选："copy"、"sync"、"bisync"
SYSTEM_STORAGE_DEPTH=2                     # 需要在存储端创建源端 DIRECTORY_* 目录则设为2，否则为1
# -- 源端
BASE_DOCKER="/home/${USER}/Documents"
DIRECTORY_DOCKER="Docker"
TARGETS_DOCKER=("backup-docker" "filter-backup" "Run" "Volume")

# Music
# -- 存储端
MUSIC_STORAGE="YJ-NAS:music" # 目标存储地址
MUSIC_STORAGE_TYPE="bisync"  # 同步类型，可选："copy"、"sync"、"bisync"
MUSIC_STORAGE_DEPTH=1        # 需要在存储端创建源端 DIRECTORY_* 目录则设为2，否则为1
# -- 源端
BASE_MUSIC="/home/${USER}"
DIRECTORY_MUSIC="Music"
TARGETS_MUSIC=("CloudMusic" "MyMusic")

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m${NAME}\x1b[0m \x1b[1m${DESC}\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     ${NAME} [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     --all            Back up All"
  echo -e "     --docker         Back up Docker"
  echo -e "     --music          Back up Music"
  echo -e ""
  echo -e "     -h, --help       View this help information"
  echo -e "     -v, --version    View version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m${NAME}\x1b[0m version (\x1b[1m${MAJOR}-${MINOR}.${RELEASE}\x1b[0m)"
}

#------------------------- Feature Function
# 确保指定文件夹存在
function checkPath() {
  if [[ -e "${1}" ]]; then
    if [[ ! -d "${1}" ]]; then
      echo -e "Path '${1}' is not a folder, exit"
      exit ${ERR_FILE}
    fi
  else
    mkdir -p "${1}"
  fi
}

# 日志函数
function logger() {
  local line

  # 无参数输出空行
  if [ $# -eq 0 ]; then
    # 无参数：输出一个空行
    printf '%b\n' ""
    printf '%s\n' "" >>"${LOGFILE}"
    return
  fi

  printf '%s\n' "${*}" | while IFS= read -r line; do
    # 控制台输出（解析 ANSI 转义）
    printf '%s %b\n' "${TIMESTAMP}" "${line}"
    # 日志输出（去除 ANSI 颜色代码）
    printf '%s %s\n' "${TIMESTAMP}" "${line}" | sed 's/\\x1b\[[0-9;]*[mGK]//g; s/\\033\[[0-9;]*[mGK]//g' >>"${LOGFILE}"
  done
}

# 备份执行器
function syncer() {
  local storage=${1}
  local storage_type=${2}
  local storage_depth=${3}
  local base=${4}
  local directory=${5}
  shift 5
  local targets=("$@")

  for target in "${targets[@]}"; do
    source_path="${base}/${directory}/${target}" # 源路径

    if [ "${storage_depth}" -eq 1 ]; then
      if [ -f "${source_path}" ]; then
        # 文件
        storage_path="${storage}" # 最终备份路径
      elif [ -d "${source_path}" ]; then
        # 文件夹
        storage_path="${storage}/${target}" # 最终备份路径
      else
        logger "WARN : ${source_path} 不是文件或文件夹，跳过"
        continue
      fi
    elif [ "${storage_depth}" -eq 2 ]; then
      if [ -f "${source_path}" ]; then
        # 文件
        storage_path="${storage}/${directory}" # 最终备份路径
      elif [ -d "${source_path}" ]; then
        # 文件夹
        storage_path="${storage}/${directory}/${target}" # 最终备份路径
      else
        logger "WARN : ${source_path} 不是文件或文件夹，跳过"
        continue
      fi
    else
      logger "WARN : STORAGE_DEPTH 不是 1 或 2，退出"
      exit ${ERR_PARAM}
    fi

    logger "INFO  : 正在备份 ${source_path} -> ${storage_path}"

    # 执行备份
    if [ "${storage_type}" == "copy" ]; then
      rclone copy --update "${source_path}" "${storage_path}" --transfers="${TRANSFER}" --log-file="${LOGFILE}" --log-level="${LOGLEVEL}"
    elif [ "${storage_type}" == "sync" ]; then
      rclone sync "${source_path}" "${storage_path}" --transfers="${TRANSFER}" --log-file="${LOGFILE}" --log-level="${LOGLEVEL}"
    elif [ "${storage_type}" == "bisync" ]; then
      rclone bisync "${source_path}" "${storage_path}" --resync --conflict-resolve="${RESOLVE}" --transfers="${TRANSFER}" --log-file="${LOGFILE}" --log-level="${LOGLEVEL}"
    else
      logger "WARN : 暂不支持 ${storage_type} 同步类型"
    fi

    # 检查状态
    backup_status=${?}
    if [ ${backup_status} -eq 0 ]; then
      logger "INFO  : 成功备份 ${source_path}"
    else
      logger "ERROR : 备份失败 ${source_path}, 错误代码 ${backup_status}"
    fi
  done
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "all,docker,music,help,version" -n "${NAME}" -- "${@}")
eval set -- "${ARGS}"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    checkPath "${LOGPATH}"
    case ${1} in
    --all)
      syncer "${SYSTEM_STORAGE}" "${SYSTEM_STORAGE_TYPE}" "${SYSTEM_STORAGE_DEPTH}" "${BASE_DOCKER}" "${DIRECTORY_DOCKER}" "${TARGETS_DOCKER[@]}"
      syncer "${MUSIC_STORAGE}" "${MUSIC_STORAGE_TYPE}" "${MUSIC_STORAGE_DEPTH}" "${BASE_MUSIC}" "${DIRECTORY_MUSIC}" "${TARGETS_MUSIC[@]}"
      shift 1
      ;;
    --docker)
      syncer "${SYSTEM_STORAGE}" "${SYSTEM_STORAGE_TYPE}" "${SYSTEM_STORAGE_DEPTH}" "${BASE_DOCKER}" "${DIRECTORY_DOCKER}" "${TARGETS_DOCKER[@]}"
      shift 1
      ;;
    --music)
      syncer "${MUSIC_STORAGE}" "${MUSIC_STORAGE_TYPE}" "${MUSIC_STORAGE_DEPTH}" "${BASE_MUSIC}" "${DIRECTORY_MUSIC}" "${TARGETS_MUSIC[@]}"
      shift 1
      ;;
    -h | --help)
      helpInfo
      shift 1
      ;;
    -v | --version)
      versionInfo
      shift 1
      ;;
    --)
      shift 1
      break
      ;;
    *)
      helpInfo
      exit ${ERR_UKNOWN}
      ;;
    esac
  done
fi
