#!/usr/bin/env bash

: << !
Name: system-checkupdates
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-05-31 00:00:00

Description: 用于检测系统软件包更新

Attentions:
- 将更新信息写入临时文件
- 外部进程读取临时文件获取更新信息
- 可配合 service 和 timer 定时获取更新信息
- 可配合 alpm-hooks 当 pacman 更新软件包时将临时文件内容清空

Depends:
- pacman-contrib
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# Program name
name=$(basename "$0")
readonly name
# Program description
readonly desc="detect system package updates"
# Program version
readonly major_version=3.0.5
readonly minor_version=20240827
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_no_program=127 # 未找到命令
readonly err_unknown=255    # 未知错误

#------------------------- Other Variable
# Path
readonly tmp_file="/tmp/$name.log"
readonly check_tool="checkupdates"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m \x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -c, --check       Detect package updates"
  echo -e "     -e, --empty       Clear temporary file contents"
  echo -e ""
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function checkFile() {
  if [[ ! -f $1 ]]; then
    touch "$1"
  fi
}

function checkCommand() {
  if command -v "$1" > /dev/null 2>&1; then
    return $normal
  else
    return $err_no_program
  fi
}

function checkUpdate() {
  if checkCommand "$check_tool"; then
    date_time=$(date +"%Y-%m-%d %H:%M:%S")
    echo "$date_time" > "$tmp_file"
    $check_tool >> "$tmp_file"
  else
    echo -e "Please install '$check_tool' first"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "cehv" --longoptions "check,empty,help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case $1 in
      -c | --check)
        checkFile "$tmp_file"
        checkUpdate
        shift 1
        ;;
      -e | --empty)
        checkFile "$tmp_file"
        : > "$tmp_file"
        shift 1
        ;;
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
