#!/usr/bin/env bash

: << !
Name: trash-empty_substitute
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2022-05-17 10:05:57

Description: 替换trash-empty命令防止不经确认直接清空回收站文件

Attentions:
-

Depends:
-
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=0.0.4
readonly minor_version=20230213
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="是trash-empty的无害化替身"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -f, --force       是否强制清空回收站"
  echo -e ""
  echo -e "     -h, --help        显示帮助信息"
  echo -e "     -v, --version     显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
}

function askQuestion() {
  while true; do
    read -e -r -p "$1"
    REPLY=${REPLY:-N}
    echo
    if [[ "$REPLY" =~ ^[Yy] ]]; then
      return 0
    elif [[ "$REPLY" =~ ^[Nn] ]]; then
      return 1
    else
      echo -e "应输入 Y/y 或 N/n\n"
    fi
  done
}
#------------------------- Feature Function
function zenityStatus() {
  if [[ -n $DISPLAY ]]; then
    zenity --question --default-cancel --text="是否确认移除回收站中的所有项目\n（这些项目将永远消失）"
  else
    askQuestion "是否确认移除回收站中的所有项目（这些项目将永远消失）[y/N]: "
  fi
  status=$?
  if [[ $status == 0 ]]; then
    if [[ -n $1 ]]; then
      /usr/bin/trash-empty -f
    else
      /usr/bin/trash-empty
    fi
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
case $1 in
  -f | --force)
    zenityStatus "$1"
    exit $normal
    ;;
  -h | --help)
    helpInfo
    exit $normal
    ;;
  -v | --version)
    versionInfo
    exit $normal
    ;;
  *)
    helpInfo
    exit $err_unknown
    ;;
esac
