#!/usr/bin/env bash

: <<!
Name: trust-app
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2024-02-23 13:18:59

Description: 使 macOS 信任指定程序

Attentions:
- 仅适用于 macOS

Depends:
-
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# Program name
NAME=$(basename "${0}")
readonly NAME
# Program description
readonly DESC="make macOS trust a specified program"
# Program version
readonly MAJOR=0.0.3
readonly MINOR=20240704
readonly RELEASE=1

#------------------------- Exit Code Variable
readonly NORMAL=0           # 一切正常
readonly ERR_FILE=1         # 文件/路径类错误
readonly ERR_NO_PROGRAM=127 # 未找到命令

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m${NAME}\x1b[0m \x1b[1m${DESC}\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     ${NAME} [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help        Show help information"
  echo -e "     -v, --version     Show version information"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m${NAME}\x1b[0m version (\x1b[1m${MAJOR}-${MINOR}.${RELEASE}\x1b[0m)"
}

#------------------------- Feature Function
function checkOS() {
  # 检测系统类型
  if [[ "${OSTYPE}" != "darwin"* ]]; then
    echo "Only supports macOS"
    exit ${ERR_NO_PROGRAM}
  fi
}

function trustApp() {
  checkOS

  # 如果${1}存在，输出1，否则输出错误
  if [[ -e ${1} ]]; then
    xattr -rd com.apple.quarantine "${1}"
    echo -e "\n\x1b[35m[✔]\x1b[0m \x1b[4;34m${1}\x1b[0m is trusted"
  else
    echo -e "\n\x1b[31m[✘]\x1b[0m \x1b[34m${1}\x1b[0m does not exist"
    exit ${ERR_FILE}
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "ahv" --longoptions "app:,help,version" -n "${NAME}" -- "${@}")
eval set -- "${ARGS}"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case ${1} in
    -h | --help)
      helpInfo
      exit ${NORMAL}
      ;;
    -v | --version)
      versionInfo
      exit ${NORMAL}
      ;;
    --)
      shift 1
      ;;
    *)
      trustApp "${2}"
      exit ${NORMAL}
      ;;
    esac
  done
fi
