#!/usr/bin/env bash

: << !
Name: terminal-time
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:53:29

Description: 对终端操作进行录屏

Attentions:
- 文件存储位置："$HOME/Documents/AppCache/terminal-time/"

Depends:
- util-linux
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.0.3
readonly minor_version=20230213
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0        # 一切正常
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于对终端操作进行录制"
# path variable
readonly timefile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.time"
readonly txtfile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.txt"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name OPTIONS"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function main() {
  ls "$timefile" &> /dev/null && rm "$timefile"
  ls "$txtfile" &> /dev/null && rm "$txtfile"

  echo -e "\033[1;34mFlash Start:\033[0m"
  script -t -a "$txtfile" 2> "$timefile"
  echo -e "\n\033[35mFlash Stop\033[0m"
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
if [[ ${#@} -lt 1 ]]; then
  main
else
  case $1 in
    -h | --help)
      helpInfo
      exit $normal
      ;;
    -v | --version)
      versionInfo
      exit $normal
      ;;
    *)
      helpInfo
      exit $err_unknown
      ;;
  esac
fi
