#!/usr/bin/env bash

: << !
Name: time-terminal
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:54:36

Description: 回放终端操作

Attentions:
- 文件存储位置："$HOME/Documents/AppCache/terminal-time/"

Depends:
- util-linux
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.0.3
readonly minor_version=20230213
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0        # 一切正常
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于回放录制的终端操作"
# path variable
readonly timefile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.time"
readonly txtfile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.txt"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name OPTIONS"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
}

#------------------------- Feature Function
function main() {
  echo -e "\\e[1;34mBacktrack Start:\\e[0m"
  scriptreplay "$timefile" "$txtfile"
  echo -e "Backtrack end"
  echo -e "\n\\e[35mBacktrack Stop\\e[0m"
  script -t -a "$txtfile" 2> "$timefile"
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
if [[ ${#@} -lt 1 ]]; then
  main
else
  case $1 in
    -h | --help)
      helpInfo
      exit $normal
      ;;
    -v | --version)
      versionInfo
      exit $normal
      ;;
    *)
      helpInfo
      exit $err_unknown
      ;;
  esac
fi
