#!/usr/bin/env bash

: << !
Name: configure-frpc
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2023-08-08 16:42:25

Description: 配置frpc（会受resolve影响启动失败）

Attentions:
-

Depends:
-
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.0.1
readonly minor_version=20230808
readonly rel_version=1

#------------------------- Exit Code Variable
readonly normal=0           # 一切正常
readonly err_file=1         # 文件/路径类错误
readonly err_no_program=127 # 未找到命令
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于配置Frpc"
# path variable
readonly frpc_exec_file="/usr/bin/frpc"
readonly frpcd_confile="/etc/systemd/system/frpc.service.d/override.conf"
# content variable
readonly override_content="[Service]\nRestart=always\nRestartSec=1s\n"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function main() {
  if [[ ! -e $frpcd_confile ]]; then
    if command -v $frpc_exec_file &> /dev/null; then
      echo -e "$override_content" > $frpcd_confile
      echo -e "请重启frpc服务"
      exit $normal
    else
      echo -e "\n未安装frpc"
      exit $err_no_program
    fi
  else
    echo -e "frpcd配置文件$frpcd_confile已存在"
    exit $err_file
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  main
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
