#!/usr/bin/env bash

: << !
Name: benchmarking
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 13:35:24

Description: 设备性能测试程序

Attentions:
-

Depends:
- hdparm
- coreutils

TODO List:
- TODO(2020-06-19 17:37)：添加设备检测，自动检测是HDD还是SSD
- TODO(2020-07-22 18:59)：添加其他设备的测试
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.1.0
readonly minor_version=20230223
readonly rel_version=1

#------------------------- Exit Code Variable
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于设备性能测试"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -c, --choose          选择测试方法"
  echo -e ""
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function hdparmTest() {
  devices=$(lsblk -Jplno NAME,TYPE)
  for disk in $(echo "$devices" | jq -r '.blockdevices[] | select(.type == "disk") | .name'); do
    for ((i = 1; i <= 3; i++)); do
      echo -e "\n$disk第$i次测试 -->"
      hdparm -Tt "$disk"
    done
  done
}

function ddTest() {
  for ((i = 1; i <= 5; i++)); do
    # 测试写入速度
    dd if=/dev/zero of=tempfile bs=1M count=1024 conv=fdatasync,notrunc status=progress
    # 测试无缓冲的读取速度
    echo 3 > /proc/sys/vm/drop_caches
    dd if=tempfile of=/dev/null bs=1M count=1024 status=progress
    # 测试有缓冲的读取速度
    dd if=tempfile of=/dev/null bs=1M count=1024 status=progress
  done
  rm tempfile
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "c:hv" --longoptions "choose:,help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case $1 in
      -c | --choose)
        case $2 in
          all)
            hdparmTest
            ddTest
            shift 1
            ;;
          dd)
            ddTest
            shift 1
            ;;
          hdparm)
            hdparmTest
            shift 1
            ;;
          --)
            shift 1
            break
            ;;
          *)
            echo -e "\n\033[31m[✘]\033[0m 未知的测试方法 $2"
            ;;
        esac
        shift 1
        ;;
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
