#!/usr/bin/env bash

: << !
Name: install-rust
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 11:09:04

Description: 安装配置rust开发环境

Attentions:
- 通过Arch Linux package安装

Depends:
- pacman
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.0.4
readonly minor_version=20230214
readonly rel_version=1

#------------------------- Exit Code Variable
readonly err_unknown=255 # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于安装配置Rust开发环境"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function main() {
  if command -v rustup &> /dev/null; then
    echo -e "\nrustup已安装，退出\n"
    exit
  else
    yay -S rustup rust-racer
  fi

  rustup default stable
  rustup show

  rustup component add rls rust-analysis rust-src rustfmt
  rustup component add clippy

  if racer complete std::io::B; then
    echo -e "\nrust插件依赖测试无误\n"
  fi
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  main
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
