#!/usr/bin/env bash

: << !
Name: polybar-launcher
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2021-07-12 09:22:54

Description: Polybar启动器

Attentions:
-

Depends:
- polybar
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program version
readonly major_version=0.2.4
readonly minor_version=20231013
readonly rel_version=1

#------------------------- Exit Code Variable
readonly err_no_program=127 # 未找到命令
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="是Polybar的启动器"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\x1b[32m$name\x1b[0m\x1b[1m$desc\x1b[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -s, --start       启动Polybar"
  echo -e "     -r, --restart     重启Polybar"
  echo -e ""
  echo -e "     -h, --help        显示帮助信息"
  echo -e "     -v, --version     显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
}

#------------------------- Feature Function
function checkCommand() {
  if ! command -v "$1" > /dev/null 2>&1; then
    echo -e "$1 未安装"
    exit $err_no_program
  fi
}
function startPolybar() { # 启动Polybar
  # 创建日志文件
  echo "---" | tee -a /tmp/polybar.log
  echo -e "<$(date '+%Y.%m.%d %H:%M:%S')> Polybar launched..." >> /tmp/polybar.log 2>&1 &

  # 启动polybar实例
  polybar --reload mypolybar >> /tmp/polybar.log 2>&1 &
}

function restartPolybar() { # 重启Polybar
  # 终止正在运行的polybar实例
  # 因为bar启用了ipc，也可以直接使用`polybar-msg`命令重启
  # killall -q polybar
  pkill polybar

  # 创建日志文件
  echo "---" | tee -a /tmp/polybar.log
  echo -e "<$(date '+%Y.%m.%d %H:%M:%S')> Polybar launched..." >> /tmp/polybar.log 2>&1 &

  # 启动polybar实例
  polybar --reload mypolybar >> /tmp/polybar.log 2>&1 &
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "srhv" --longoptions "start,restart,help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  helpInfo
else
  while true; do
    case $1 in
      -s | --start)
        checkCommand "polybar"
        startPolybar
        shift 1
        ;;
      -r | --restart)
        checkCommand "polybar"
        restartPolybar
        shift 1
        ;;
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
