#!/usr/bin/env bash

: << !
Name: backup-sddm-theme
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2020-04-27 10:57:48

Description: 备份sddm的主题文件

Attentions:
- 拒绝在root权限下执行

Depends:
- tar
!

####################################################################
#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
####################################################################
#------------------------- Program Variable
# program name
name=$(basename "$0")
readonly name
# program nversion
readonly major_version=0.0.4
readonly minor_version=20230214
readonly rel_version=1

#------------------------- Exit Code Variable
readonly err_file=1         # 文件/路径类错误
readonly err_permission=110 # 权限错误
readonly err_unknown=255    # 未知错误

#------------------------- Parameter Variable
# description variable
readonly desc="用于备份SDDM的主题文件"
# path variable
readonly themepath="/usr/share/sddm/themes"
readonly backupdir="$HOME/Documents/MyRepos/System-Conf/confile/usr/share/sddm"

####################################################################
#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
####################################################################
#------------------------- Info Function
function helpInfo() {
  echo -e ""
  echo -e "\033[32m$name\033[0m\033[1m$desc\033[0m"
  echo -e "--------------------------------------------------"
  echo -e "Usage:"
  echo -e ""
  echo -e "     $name [OPTION]"
  echo -e ""
  echo -e "Options:"
  echo -e "     -h, --help            显示帮助信息"
  echo -e "     -v, --version         显示版本信息"
}

function versionInfo() {
  echo -e ""
  echo -e "\033[1m$name\033[0m version (\033[1m$major_version-$minor_version.$rel_version\033[0m)"
}

#------------------------- Feature Function
function checkUser() {
  if [[ $USER == "$1" ]]; then
    echo -e "\n\\033[31m[✘]\\033[0m 当前用户是$1，拒绝执行！！！"
    exit $err_permission
  fi
}

function main() {
  if [[ -d $backupdir ]]; then
    # sddm-themes
    cd "$backupdir" || exit $err_file
    cp -r "$themepath" "$backupdir" && tar -czv --file="$PWD/themes.tgz" ./themes && rm -r "$PWD/themes"
    echo -e "\nsddm Theme备份完成\n"
  else
    mkdir -p "$backupdir"
    # sddm-themes
    cp -r "$themepath" "$backupdir" && tar -czv --file="$PWD/themes.tgz" ./themes && rm -r "$PWD/themes"
    echo -e "\nsddm Theme备份完成\n"
  fi

  echo -e "备份文件夹: $backupdir\n"
}

####################################################################
#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
####################################################################
ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
eval set -- "$ARGS"

if [[ ${#@} -lt 2 ]]; then
  checkUser "root"
  main
else
  while true; do
    case $1 in
      -h | --help)
        helpInfo
        shift 1
        ;;
      -v | --version)
        versionInfo
        shift 1
        ;;
      --)
        shift 1
        break
        ;;
      *)
        helpInfo
        exit $err_unknown
        ;;
    esac
  done
fi
